source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'GaugeView_Example' do
  pod "GaugeView", :path => "../"
end

target 'GaugeView_Tests' do
  pod "GaugeView", :path => "../"
end
